term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.orange)
print("____ ____ ____ _  _ ____")
print("|  | |__/ |__| |- | | __")
print("|__| |  | |  | | -| |__]")
print("")
print("LOADING OPERATING SYSTEM.")
sleep(1)
textutils.slowPrint("####################")
sleep(1)
shell.run(".menu")